// <auto-generated />
using System;
using CineMania.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CineMania.Migrations
{
    [DbContext(typeof(CinemaniaContext))]
    [Migration("20210922205627_add migration")]
    partial class addmigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.7");

            modelBuilder.Entity("CineMania.Models.Contact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("TEXT");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Contacts");
                });

            modelBuilder.Entity("CineMania.Models.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Common tropes of the genre include explosions, car chases, fistfights and shootouts. This genre is closely associated with the thriller and adventure genres and may also contain elements of drama and spy fiction.[2] Screenwriter and scholar Eric R. Williams identifies Action Film as one of eleven super-genres struggling against incredible odds, which include life-threatening situations struggling against incredible odds, which include life-threatening situations",
                            Genre = "FOREVER MORE",
                            ImageName = "8.jpg",
                            ReleaseDate = new DateTime(1980, 11, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "FLINT"
                        },
                        new
                        {
                            Id = 2,
                            Description = "It’s largely a matter of opinion, but some titles are remembered long after the movie leaves theaters thanks to the way they roll off the tongue and stand out among all the other titles",
                            Genre = "Patrik's movies",
                            ImageName = "no country.jpg",
                            ReleaseDate = new DateTime(2017, 11, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "No Country for old men"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Action film is a film genre in which the protagonist or protagonists are thrust into a series of events that typically include violence, extended fighting, physical feats, rescues and frantic chases. and scholar Eric R. Williams identifies Action Film as one of eleven super-genres",
                            Genre = "HEY-YOU",
                            ImageName = "scaarface.jpg",
                            ReleaseDate = new DateTime(1980, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "SCARFACE SERIES"
                        },
                        new
                        {
                            Id = 4,
                            Description = "rescues and frantic chases. Action films tend to feature a mostly resourceful hero struggling against incredible odds, which include life-threatening situations,a dangerous villain, or a pursuit which usually concludes in victory for the hero. Advancements in computer-generated imagery (CGI) have made it cheaper and easier to create",
                            Genre = "HOLLY WOOD",
                            ImageName = "die hard.jpg",
                            ReleaseDate = new DateTime(2002, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "DIE HARD"
                        },
                        new
                        {
                            Id = 5,
                            Description = "framed him as the archetypal hero of the urban action film. In many countries, restrictions on language, adult content, and violence had loosened up, and these elements became more widespread. In the 1970s, martial arts films",
                            Genre = "BRIDAL SERIES",
                            ImageName = "6.jpg",
                            ReleaseDate = new DateTime(2002, 6, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "BRIDAL MASK"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Hollywood co-production, Bruce Lee's Enter the Dragon (1973). Lee's death the same year led to a wave of Bruceploitation films in Asian cinema, a trend that eventually came to an end with the success of several kung fu action-comedy films released in 1978: Jackie Chan's Snake in the Eagle's Shadow and Drunken Master, and Sammo Hung's Enter the Fat Dragon",
                            Genre = "HEY-YOU",
                            ImageName = "OLD G.jpg",
                            ReleaseDate = new DateTime(2011, 6, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "OLD GUARD"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Like the Western genre, spy-movies, as well as urban-action films, were starting to parody themselves, and with the growing revolution in CGI (computer generated imagery), the real-world settings began to give way to increasingly fantastic environments.This new era of action films often had budgets unlike any in the history of motion pictures.[24] The success of the many Dirty Harry and James Bond sequels had proven that a single successful action film could lead to a continuing action franchise. Thus, the 1980s and 1990s saw a rise in both budgets and the number of sequels a film could generally have.[25] This led to an increasing number of filmmakers to create new technologies that would allow them to beat the",
                            Genre = "WOW FILMS",
                            ImageName = "4.jpg",
                            ReleaseDate = new DateTime(2010, 6, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "NO BODY IN THIS WORLD"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
